routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(); 
Route::resource('post', 'PostController');  
Route::resource('feed', 'FeedController');  
Route::get('profile','UsersController@index');   
Route::post('updateprofile','UsersController@updateProfile')->name('profile.update'); 
Route::post('updatecomment','FeedController@updateComment')->name('updatecomment'); 

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    protected $fillable = [
        'title', 'content', 'user_id'
    ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Posts;
use App\Models\Comments;
use Illuminate\Support\Facades\Auth;
use Validator;
use Session;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource. 
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $posts = Posts::where('user_id', '=', Auth::user()->id)->get();
        return view('admin.posts.index', ['posts' => $posts]);
    } 

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $custom_validation_messages = array(
            'title.required' => "El titulo es requerido.",
            'title.min' => "El titulo no puede tener menos de 3 caracteres.",
            'content.required' => "El contenido es requerido.",
            'content.min' => "El contenido no puede tener menos de 4 caracteres."
          );

          $validator = Validator::make($request->all(), [
            "title" => 'required|min:3',
            "content" => 'required|min:4'

        ],$custom_validation_messages);

        if ($validator->fails()) {
            return back()
                   ->withErrors($validator)
                   ->withInput();
        }

         
        $post =  Posts::create([
            'title' => $request->title,
            'content' => $request->content,
            'user_id' => Auth::user()->id
        ]); 

        Session::flash('message', 'Post creado');
        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       
        $post =  Posts::find($id);
        return view('admin.posts.edit', ['post' => $post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $custom_validation_messages = array(
            'title.required' => "El titulo es requerido.",
            'title.min' => "El titulo no puede tener menos de 3 caracteres.",
            'content.required' => "El contenido es requerido.",
            'content.min' => "El contenido no puede tener menos de 4 caracteres."
          );

          $validator = Validator::make($request->all(), [
            "title" => 'required|min:3',
            "content" => 'required|min:4'

        ],$custom_validation_messages);

        if ($validator->fails()) {
            return back()
                   ->withErrors($validator)
                   ->withInput();
        }

         
        $post =  Posts::find($id);
        $post->title = $request->title;
        $post->content = $request->content; 
        $post->save(); 
    

        Session::flash('message', 'Post editado');
        return redirect()->route('post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post =  Posts::find($id);
        if($post){
            Comments::where('post_id',$id)->delete();
            $post->delete();
            Session::flash('message', 'Post eliminado');
            return redirect()->route('post.index');
        }else{
            Session::flash('error-message', 'Post no encontrado');
            return redirect()->route('post.index');
        }
        return redirect()->back();


    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.layout')

@section('content')
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Crear post</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start --> 
              <form method="post" role="form" action="{{route('post.store')}}">
              {{csrf_field()}}
                <div class="card-body">
                  <div class="form-group">
                    <label for="title">Titulo</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Ingrese titulo" value="{{ old('title') }}" required>
                  </div>
                  @error('title') 
                    <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  <div class="form-group">
                    <label for="content">Contenido</label> 
                    <textarea class="form-control" rows="3" id="content" name="content" placeholder="Ingrese contenido" required>{{ old('content') }}</textarea>
                  </div>
                  @error('content') 
                    <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>


@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.layout')

@section('content')
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Editar post</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start --> 
              <form method="POST" role="form" action="{{route('post.update',$post->id)}}">
              {{csrf_field()}}
              @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="title">Titulo</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Ingrese titulo" value="{{ $post->title }}" required>
                  </div>
                  @error('title') 
                    <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  <div class="form-group">
                    <label for="content">Contenido</label> 
                    <textarea class="form-control" rows="3" id="content" name="content" placeholder="Ingrese contenido" required>{{ $post->content }}</textarea>
                  </div>
                  @error('content') 
                    <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>


@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.layout')

@section('content')

<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
              @if(Session::has('message')) 
                <p class="alert alert-success">{{ Session::get('message') }}</p>
              @endif
              @if(Session::has('error-message')) 
                <p class="alert alert-danger">{{ Session::get('error-message') }}</p>
              @endif
                <h3 class="card-title">Mis post</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="table" class="table table-bordered table-striped">
                 <thead>
                  <tr>
                   <th>#</th>
                   <th>Titulo</th>
                   <th></th>
                   </tr>
                 </thead>
                 <tbody>
                 @foreach($posts as $key => $post)
                  <tr>
                  <td>{{$key +1}}</td>
                  <td>{{$post->title}}</td>
                  <td>
                   <div class="container">
                    <div class="row">
                     <a href="{{route('post.edit',$post->id)}}" class="col-lg-2 btn btn-info load "><i class="fas fa-edit"></i></a>
                     <a onclick="event.preventDefault();document.getElementById('delete-post-{{$post->id}}').submit();"  class="col-lg-2 btn btn-danger load "><i class="fas fa-trash"></i></a>
                     <form action="{{ route('post.destroy', $post->id) }}" id="delete-post-{{$post->id}}" method="POST">
                       @method('DELETE')
                       @csrf 
                     </form>
                    </div>
                   </div>
                  </td>
                 </tr>
                 @endforeach
                 </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
 
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>

@endsection