routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(); 
Route::resource('post', 'PostController');  
Route::resource('feed', 'FeedController');  
Route::get('profile','UsersController@index');   
Route::post('updateprofile','UsersController@updateProfile')->name('profile.update'); 
Route::post('updatecomment','FeedController@updateComment')->name('updatecomment'); 

app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Posts;
use App\Models\Comments; 
use Illuminate\Support\Facades\Auth;
use Validator;
use Session;


class FeedController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Posts::orderBy('created_at', 'desc')->get();
        return view('admin.feed.index', ['posts' => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post =  Posts::find($id);
        $comments = Comments::where('post_id',$id)->get();
        return view('admin.feed.show', ['post' => $post, 'comments' => $comments]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(auth()->user()->can('editar-post')){
        $post =  Posts::find($id);
        $comments = Comments::where('post_id',$id)->get();
        return view('admin.feed.edit', ['post' => $post, 'comments' => $comments]);
        }else{
            Session::flash('error-message', 'No tiene permiso para ingresar en esta sección.');
            return redirect()->route('feed.index');

        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $custom_validation_messages = array(
            'title.required' => "El titulo es requerido.",
            'title.min' => "El titulo no puede tener menos de 3 caracteres.",
            'content.required' => "El contenido es requerido.",
            'content.min' => "El contenido no puede tener menos de 4 caracteres."
          );

          $validator = Validator::make($request->all(), [
            "title" => 'required|min:3',
            "content" => 'required|min:4'

        ],$custom_validation_messages);

        if ($validator->fails()) {
            return back()
                   ->withErrors($validator)
                   ->withInput();
        } 


        if(auth()->user()->can('editar-post')){  
        $post =  Posts::find($id);
        $post->title = $request->title;
        $post->content = $request->content; 
        $post->save(); 

        }

        if(isset($request->comment)){
            Comments::create([
                'post_id' => $id,
                'comment' => $request->comment,
                'user_id' => Auth::user()->id,
               ]); 
        }

         
        Session::flash('message', 'Cambios realizados');
        return redirect()->route('feed.index');

        
   
    }
 

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment =  Comments::find($id);
        if($comment){ 
            $comment->delete();
            Session::flash('message', 'Comentario eliminado');
            return redirect()->back();
        }else{
            Session::flash('error-message', 'Comentario no encontrado');
            return redirect()->back();
        }
        return redirect()->back();
    }
}

resources/views/admin/feed/edit.blade.php
@extends('layouts.layout')

@section('content')
          <div class="card card-primary">
            <div class="card-header">
             <h3 class="card-title">Editar Feed post</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start --> 
            <form method="POST" role="form" action="{{route('feed.update',$post->id)}}">
            {{csrf_field()}}
            @method('PUT')
            <div class="card-body">
             <div class="form-group">
                <label for="title">Titulo</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Ingrese titulo" value="{{ $post->title }}" required>
            </div>
            @error('title') 
             <div class="alert alert-danger">{{ $message }}</div>
            @enderror
             <div class="form-group">
              <label for="content">Contenido</label> 
              <textarea class="form-control" rows="3" id="content" name="content" placeholder="Ingrese contenido" required>{{ $post->content }}</textarea>
             </div>
            @error('content') 
             <div class="alert alert-danger">{{ $message }}</div>
            @enderror  
           <div class="card-footer">
            <button type="submit" class="btn btn-primary">Enviar datos</button>
           </div>
          </form>
          <div class="card card-warning">
              <div class="card-header">
                <h3 class="card-title">Comentarios</h3>
              </div>
              <div class="card-body" id="dinamic-comment">
              @foreach($comments as $key => $comment)
              @if($comment->user_id == Auth::user()->id)
              <div class="row mt-3 div-parent">
                  <div class="col-10">
                  <textarea class="form-control" rows="2" placeholder="Ingrese comentario" disabled>{{$comment->comment}}</textarea>
                  <i>Autor: {{$comment->getUser->name}}</i>
                  </div>
                  <div class="col-2">
                  <a href="{{ route('feed.destroy', $comment->id) }}" onclick="event.preventDefault();document.getElementById('delete-comment-{{$comment->id}}').submit();"  class="btn btn-danger pull-right"><i class="fas fa-trash"></i>
                  </a>
                     <form action="{{ route('feed.destroy', $comment->id) }}" id="delete-comment-{{$comment->id}}" method="POST">
                       @method('DELETE')
                       @csrf 
                     </form> 
                  </div>
                </div>
                @else
                @can('editar-post') 
                <div class="row mt-3 div-parent">
                  <div class="col-10">
                  <textarea class="form-control" rows="2" placeholder="Ingrese comentario" disabled>{{$comment->comment}}</textarea>
                  <i>Autor: {{$comment->getUser->name}}</i>
                  </div>
                  <div class="col-2">
                  <a href="{{ route('feed.destroy', $comment->id) }}" onclick="event.preventDefault();document.getElementById('delete-comment-{{$comment->id}}').submit();"  class="btn btn-danger pull-right"><i class="fas fa-trash"></i>
                  </a>
                     <form action="{{ route('feed.destroy', $comment->id) }}" id="delete-comment-{{$comment->id}}" method="POST">
                       @method('DELETE')
                       @csrf 
                     </form> 
                  </div>
                </div>
                @else
                <div class="row mt-3">
                  <div class="col-12">
                  <textarea class="form-control" rows="2" name="" placeholder="Ingrese comentario" disabled>{{$comment->comment}}</textarea>
                  <i>Autor: {{$comment->getUser->name}}</i>
                  </div>
                </div>

                @endcan

                @endif
                
              @endforeach
              <br>
              </div>
             
            </div>  
         </div>
         </div>


@endsection
 

resources/views/admin/feed/index.blade.php
@extends('layouts.layout')

@section('content')

<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
              @if(Session::has('message')) 
                <p class="alert alert-success">{{ Session::get('message') }}</p>
              @endif
              @if(Session::has('error-message')) 
                <p class="alert alert-danger">{{ Session::get('error-message') }}</p>
              @endif
                <h3 class="card-title">Mis post</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="table" class="table table-bordered table-striped">
                 <thead>
                  <tr>
                   <th>#</th>
                   <th>Titulo</th>
                   <th></th>
                   </tr>
                 </thead>
                 <tbody>
                 @foreach($posts as $key => $post)
                  <tr>
                  <td>{{$key +1}}</td>
                  <td>{{$post->title}}</td>
                  <td>
                   <div class="container">
                    <div class="row">

                    <a href="{{route('feed.show',$post->id)}}" class="col-lg-2 btn btn-warning load "><i class="fas fa-eye"></i></a>
                    @can('editar-post')
                     <a href="{{route('feed.edit',$post->id)}}" class="col-lg-2 btn btn-info load "><i class="fas fa-edit"></i></a>
                     @endcan
                     @can('eliminar-post')
                     <a onclick="event.preventDefault();document.getElementById('delete-post-{{$post->id}}').submit();"  class="col-lg-2 btn btn-danger load "><i class="fas fa-trash"></i></a>
                     <form action="{{ route('post.destroy', $post->id) }}" id="delete-post-{{$post->id}}" method="POST">
                       @method('DELETE')
                       @csrf 
                     </form>
                     @endcan
                    </div>
                   </div>
                  </td>
                 </tr>
                 @endforeach
                 </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
 
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>

@endsection

resources/views/admin/feed/show.blade.php
@extends('layouts.layout')

@section('content')
          <div class="card card-primary">
          @if(Session::has('message')) 
                <p class="alert alert-success">{{ Session::get('message') }}</p>
              @endif
              @if(Session::has('error-message')) 
                <p class="alert alert-danger">{{ Session::get('error-message') }}</p>
              @endif
            <div class="card-header">
             <h3 class="card-title">Feed post</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start --> 
            <form method="POST" role="form" action="{{route('feed.update',$post->id)}}">
            {{csrf_field()}}
            @method('PUT')
            <div class="card-body">
             <div class="form-group">
                <label for="title">Titulo</label>
                <input type="text" class="form-control" id="title" placeholder="Ingrese titulo" value="{{ $post->title }}" disabled>
                <input type="hidden" name="title" value="{{ $post->title }}">
            </div>
 
             <div class="form-group">
              <label for="content">Contenido</label> 
              <textarea class="form-control" rows="3" id="content" placeholder="Ingrese contenido" disabled>{{ $post->content }}</textarea>
              <input type="hidden" name="content" value="{{ $post->title }}">
             </div>
  
              <div class="card-header">
                <h3 class="card-title">Agregar comentario</h3>
              </div>
              <div class="card-body" id="dinamic-comment">
                <div class="row mt-3 div-parent">
                  <div class="col-12">
                  <textarea class="form-control" rows="2" name="comment" placeholder="Ingrese comentario" ></textarea>
                  @error('comment') 
                    <div class="alert alert-danger">{{ $message }}</div>
                  @enderror
                  </div>
                </div> 
             
            </div>   
           <div class="card-footer">
            <button type="submit" class="btn btn-success">Enviar datos</button>
           </div>
          </form>
          <br>
          <div class="card card-warning">
              <div class="card-header">
                <h3 class="card-title">Comentarios</h3>
              </div>
              <div class="card-body" id="dinamic-comment">
              @foreach($comments as $key => $comment)
              @if($comment->user_id == Auth::user()->id)
              <div class="row mt-3 div-parent">
                  <div class="col-10">
                  <textarea class="form-control" rows="2" placeholder="Ingrese comentario" disabled>{{$comment->comment}}</textarea>
                  <i>Autor: {{$comment->getUser->name}}</i>
                  </div>
                  <div class="col-2">
                  <a href="{{ route('feed.destroy', $comment->id) }}" onclick="event.preventDefault();document.getElementById('delete-comment-{{$comment->id}}').submit();"  class="btn btn-danger pull-right"><i class="fas fa-trash"></i>
                  </a>
                     <form action="{{ route('feed.destroy', $comment->id) }}" id="delete-comment-{{$comment->id}}" method="POST">
                       @method('DELETE')
                       @csrf 
                     </form> 
                  </div>
                </div>
                @else
                @can('editar-post') 
                <div class="row mt-3 div-parent">
                  <div class="col-10">
                  <textarea class="form-control" rows="2" placeholder="Ingrese comentario" disabled>{{$comment->comment}}</textarea>
                  <i>Autor: {{$comment->getUser->name}}</i>
                  </div>
                  <div class="col-2">
                  <a href="{{ route('feed.destroy', $comment->id) }}" onclick="event.preventDefault();document.getElementById('delete-comment-{{$comment->id}}').submit();"  class="btn btn-danger pull-right"><i class="fas fa-trash"></i>
                  </a>
                     <form action="{{ route('feed.destroy', $comment->id) }}" id="delete-comment-{{$comment->id}}" method="POST">
                       @method('DELETE')
                       @csrf 
                     </form> 
                  </div>
                </div>
                @else
                <div class="row mt-3">
                  <div class="col-12">
                  <textarea class="form-control" rows="2" name="" placeholder="Ingrese comentario" disabled>{{$comment->comment}}</textarea>
                  <i>Autor: {{$comment->getUser->name}}</i>
                  </div>
                </div>

                @endcan

                @endif
                
              @endforeach
              <br>
              </div>
             
            </div>  
         </div>


@endsection
 